import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";
import "bootstrap/dist/css/bootstrap.min.css";
import React, { useRef, useState } from "react";
import { useForm } from "react-hook-form";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  type FormData = {
    name: string;
    email: string;
    message: string;
  };

  const { register, handleSubmit, formState: { errors } } = useForm<FormData>();

  const onSubmit = async (data) => {
    console.log(data)
    console.log(JSON.stringify(data))
    console.log("メール送信")
    await fetch("api/contact", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain",
        "Content-Type": "application/json"
      },
      body: JSON.stringify(data),
    }).then((res) => {
      if (res.status === 200) console.log("送信に成功しました");
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5 ">
        <h2 className="mb-3">Next.jsでメール送信</h2>
        <form
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="mb-3">
            <label className="form-label" htmlFor="name">
              お名前
            </label>
            <input
              className="form-control"
              type="text"
              id="name"
              required
              {...register('name')}
            />
          </div>
          <div className="mb-3">
            <label className="form-label" htmlFor="email">
              メールアドレス
            </label>
            <input
              className="form-control"
              type="email"
              id="email"
              required
              {...register('email')} 
            />
          </div>
          <div className="mb-3">
            <label className="form-label" htmlFor="message">
              メッセージ
            </label>
            <textarea
              className="form-control"
              id="message"
              required
              {...register('message')}
            />
          </div>
          <button className="btn btn-danger" type="submit">
            メール送信
          </button>
        </form>
      </div>
    </>
  )
}
